import { NextResponse } from 'next/server'
import { encryptSecret } from '@/lib/crypto'
import { getAuthenticatedUser } from '@/lib/supabase-server'
import { TeslaApiError } from '@/lib/tesla/errors'
import { createAuthorizationRequest, decodeTeslaToken, verifyAccessToken } from '@/lib/tesla/auth'
import { readCredential, saveTokenSet } from '@/lib/tesla/tokens'
import { syncVehiclesFromList } from '@/lib/tesla/service'
import { TeslaClient } from '@/lib/tesla/client'
import { teslaConfig } from '@/lib/tesla/config'
import { recordRequest } from '@/lib/tesla/request-log'

export const dynamic = 'force-dynamic'

/**
 * §16 "Connect Tesla".
 *
 * GET starts the real PKCE flow: `state` and `code_verifier` are generated here and
 * stored encrypted in an httpOnly cookie, so the verifier never reaches page
 * JavaScript (§15). Because `client_id=ownerapi` only echoes the code to Tesla's own
 * void callback, completion happens by pasting that callback URL to
 * /api/tesla/auth/complete — there is no way to register our redirect URI with
 * Tesla's native client, and pretending otherwise would mean inventing a flow.
 */
export async function GET(request: Request) {
  const user = await getAuthenticatedUser()
  if (!user) return NextResponse.redirect(new URL('/login', request.url))

  const authorization = createAuthorizationRequest()
  const response = NextResponse.redirect(authorization.url)
  response.cookies.set('tesla_owner_oauth', encryptSecret(JSON.stringify({ state: authorization.state, codeVerifier: authorization.codeVerifier, createdAt: authorization.createdAt })), {
    httpOnly: true,
    maxAge: 600,
    path: '/',
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
  })
  return response
}

type ConnectBody = { accessToken?: string; refreshToken?: string }

/**
 * Secondary path from §16: paste an access+refresh pair generated by an external
 * desktop app (the TeslaMate approach). Nothing here ever accepts a password.
 */
export async function POST(request: Request) {
  const user = await getAuthenticatedUser()
  if (!user) return NextResponse.json({ message: 'Требуется вход в приложение' }, { status: 401 })

  let body: ConnectBody
  try {
    body = await request.json() as ConnectBody
  } catch {
    return NextResponse.json({ message: 'Некорректное тело запроса' }, { status: 400 })
  }
  const accessToken = body.accessToken?.trim()
  const refreshToken = body.refreshToken?.trim()
  if (!accessToken || !refreshToken) {
    return NextResponse.json({ message: 'Нужны обе строки: access token и refresh token из Tesla Auth' }, { status: 400 })
  }

  let claims: ReturnType<typeof decodeTeslaToken>
  try {
    claims = decodeTeslaToken(accessToken)
  } catch (error) {
    return NextResponse.json({ message: error instanceof Error ? error.message : 'Токен не разбирается как JWT' }, { status: 400 })
  }
  if (claims.azp && claims.azp !== teslaConfig.clientId) {
    return NextResponse.json({
      message: `Токен выдан клиентом «${claims.azp}», а Owner API принимает ownerapi. Сгенерируйте пару заново в Tesla Auth.`,
      reason: 'wrong_client_id',
    }, { status: 422 })
  }

  // Liveness first: SSO answers even when the Owner API host itself is gated, which
  // is the difference between "bad credentials" and "Tesla closed this route".
  const authHost = claims.iss ? safeHost(claims.iss) : null
  const verified = await verifyAccessToken(accessToken, authHost ? `https://${authHost}${teslaConfig.authPath}` : undefined)
  if (!verified.ok) {
    return NextResponse.json({
      message: `Tesla отклонила access token (${verified.status}). Обновите пару токенов в Tesla Auth.`,
      reason: 'token_rejected',
    }, { status: 422 })
  }

  const provisional = new TeslaClient({
    getAccessToken: async () => accessToken,
    onLog: (entry) => void recordRequest({ ...entry, vehicleId: entry.vehicleId }),
    cacheTtlMs: 0,
  })

  let vehicleSync = { count: 0, status: 'unavailable' as 'ok' | 'unavailable', reason: null as string | null }
  try {
    const list = await provisional.getVehicles()
    const synced = await syncVehiclesFromList(user.id, list)
    vehicleSync = { count: synced.count, status: 'ok', reason: null }
  } catch (error) {
    if (error instanceof TeslaApiError && error.kind === 'forbidden') {
      vehicleSync = { count: 0, status: 'unavailable', reason: 'Tesla закрыла доступ к Owner API для этого токена (403). Учётные данные сохранены — как только доступ вернётся, сбор заработает.' }
    } else {
      vehicleSync = { count: 0, status: 'unavailable', reason: error instanceof Error ? error.message.slice(0, 200) : 'Список автомобилей не получен' }
    }
  }

  // The credential is valid at the SSO layer, so it is stored even when the vehicle
  // list could not be fetched: re-pasting a working pair should not be necessary.
  const existing = await firstVehicleId(user.id)
  const credentialVehicleId = existing ?? (await createPlaceholderVehicle(user.id))

  if (credentialVehicleId) {
    await saveTokenSet({
      vehicleId: credentialVehicleId,
      ownerId: user.id,
      tokenSet: { access_token: accessToken, refresh_token: refreshToken },
      authHost,
    })
  }

  return NextResponse.json({
    connected: true,
    credentialVehicleId,
    vehicles: vehicleSync,
    tokenClaims: { azp: claims.azp, scopes: claims.scp, expiresAt: claims.exp ? new Date(claims.exp * 1000).toISOString() : null },
    message: vehicleSync.status === 'ok'
      ? `Tesla подключена. Найдено автомобилей: ${vehicleSync.count}.`
      : vehicleSync.reason,
  })
}

function safeHost(issuer: string): string | null {
  try {
    const url = new URL(issuer)
    return teslaConfig.isTrustedAuthHost(url.hostname) ? url.hostname : null
  } catch {
    return null
  }
}

async function firstVehicleId(ownerId: string): Promise<string | null> {
  const { listVehicleRows } = await import('@/lib/tesla/service')
  const rows = await listVehicleRows(ownerId)
  return rows[0]?.id ?? null
}

/**
 * When the vehicle list is unavailable we still need a row to hang the credential
 * on, because `vehicle_credentials.vehicle_id` references `vehicles.id`. The row is
 * marked so the UI can show «автомобиль не подтверждён» instead of inventing one.
 */
async function createPlaceholderVehicle(ownerId: string): Promise<string | null> {
  const { getSupabaseAdmin } = await import('@/lib/supabase')
  const supabase = getSupabaseAdmin()
  const { data, error } = await supabase.from('vehicles').insert({
    owner_id: ownerId,
    provider_vehicle_id: `pending:${Date.now()}`,
    display_name: 'Tesla (не подтверждён)',
    model: null,
  }).select('id').single()
  if (error || !data) return null
  return String(data.id)
}

/** §16 connection status for the /connect screen. */
export async function DELETE(request: Request) {
  const user = await getAuthenticatedUser()
  if (!user) return NextResponse.json({ message: 'Требуется вход в приложение' }, { status: 401 })
  const { getSupabaseAdmin } = await import('@/lib/supabase')
  const supabase = getSupabaseAdmin()
  const { error } = await supabase.from('vehicle_credentials').delete().eq('owner_id', user.id)
  if (error) return NextResponse.json({ message: error.message }, { status: 500 })
  return NextResponse.json({ disconnected: true })
}

/** Re-read the stored credential's shape without exposing it (§16 "Tesla connected"). */
export async function PUT(request: Request) {
  const user = await getAuthenticatedUser()
  if (!user) return NextResponse.json({ message: 'Требуется вход в приложение' }, { status: 401 })
  const { listVehicleRows } = await import('@/lib/tesla/service')
  const rows = await listVehicleRows(user.id)
  const credential = rows[0] ? await readCredential(rows[0].id, user.id) : null
  return NextResponse.json({
    connected: Boolean(credential),
    vehicleCount: rows.length,
    vehicles: rows.map((row) => ({ id: row.id, name: row.display_name, ownerApiId: row.owner_api_id ?? null })),
    expiresAt: credential?.expiresAt ?? null,
    scopes: credential?.scopes ?? null,
    authHost: credential?.authHost ?? null,
  })
}
